import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";

import { getCategories } from "@/app/_queries/get-categories";
import AuthUserAvatar from "@/components/auth-user-avatar";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const categoriesData = await getCategories();

	return (
		<html lang="en">
			<body className={cn("container max-w-7xl pb-5", inter.className)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<nav className="flex gap-5 py-5 justify-between items-center">
						<div>
							<Button variant="ghost" asChild>
								<Link href="/">Home</Link>
							</Button>
							{categoriesData.map((category) => (
								<Button variant="ghost" asChild key={category.id}>
									<Link href={`/categories/${category.id}`}>
										{category.name}
									</Link>
								</Button>
							))}
						</div>
						<AuthUserAvatar />
					</nav>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
